server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dlwltjd7778/config-server  # ????? ?? ???
          default-label: main                               # ? ?? ????
          search-paths: config-file/**                        # ???? ?? ??
