com:
  jiseong:
    config-test: test!7!!!

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

# config 설정 변경 시 fetch를 위한 래빗Mq 설정 (busrefresh)
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
